# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.redhat.openjdk.buildpacks.buildpack"
version = "0.0.1"
name = "OpenJDK Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "com.redhat.openjdk.buildpacks.stack.jvm"
